name: "Simple Tools Server"
icon: "assets/icon.jpg"
description: "Dummy server template for MCP implementation"
documentation_path: "README.md"
tools:
  - name: "Tools 1"
    description: "Tools 1 description"
