name: "Discord GuMCP Server"
icon: "assets/icon.png"
description: "Server for interacting with Discord channels, messages, and users"
documentation_path: "README.md"
tools:
  - name: "send_message"
    description: "Send a message to a Discord channel"
  - name: "read_messages"
    description: "Read recent messages from a Discord channel"
  - name: "add_reaction"
    description: "Add a reaction to a message"
  - name: "edit_message"
    description: "Edit an existing message sent by the bot"
  - name: "delete_message"
    description: "Delete a message from a channel"
  - name: "send_embed"
    description: "Send a rich embed message to a channel"
  - name: "get_user_info"
    description: "Retrieve information about a user"
  - name: "send_dm"
    description: "Send a direct message to a user"
  - name: "ban_member"
    description: "Ban a member from a server"
  - name: "kick_member"
    description: "Kick a member from a server"
  - name: "mute_member"
    description: "Mute or unmute a member in voice channels"
  - name: "assign_role"
    description: "Add or remove a role from a member"
  - name: "list_members"
    description: "Get a list of members in a server"
