name: "Google Drive GuMCP Server"
icon: "assets/icon.png"
description: "Server for interacting with Google Drive files and documents"
documentation_path: "README.md"
tools:
  - name: "search"
    description: "Search for files in Google Drive"
